node {
   def mvnHome
   stage('Preparation') { // for display purposes
      // Get some code from a GitHub repository
      checkout scm
      // Get the Maven tool.
      // ** NOTE: This 'M3' Maven tool must be configured
      // **       in the global configuration.
      mvnHome = tool 'M3'
   }
   dir('tomcat-websocket-chat'){
   stage('Build') {
      // Run the maven build
      if (isUnix()) {
         sh "'${mvnHome}/bin/mvn' -s ../settings.xml -Dmaven.test.failure.ignore clean package"
      } else {
         bat(/"${mvnHome}\bin\mvn" -Dmaven.test.failure.ignore clean package/)
      }
   }
   stage('Results') {
      archive '**/target/*.war'
   }
	}
   
	stage('OSE BUILD ;-)'){
       env.SKIP_TLS=true
   sh 'oc login https://manage.cloud.itandtel.at --token=UnAlPRynbZZHmAtDpEb0zJiqKUlKTnopS10yK84UVsQ'
   sh "oc env -n 48-thomas-test bc/jws-app1 BUILD_NUMBER=${env.BUILD_NUMBER}"
  openshiftBuild apiURL: 'https://manage.cloud.itandtel.at/', authToken: 'UnAlPRynbZZHmAtDpEb0zJiqKUlKTnopS10yK84UVsQ',
     bldCfg: 'jws-app1', buildName: '', checkForTriggeredDeployments: 'false', commitID: '', namespace: '48-thomas-test',
     showBuildLogs: 'true', verbose: 'true', waitTime: ''
   }
   
   stage('Verify Deployment') {
	openshiftVerifyDeployment apiURL: 'https://manage.cloud.itandtel.at/', authToken: 'UnAlPRynbZZHmAtDpEb0zJiqKUlKTnopS10yK84UVsQ', 
	depCfg: 'jws-app1', namespace: '48-thomas-test', replicaCount: '1', verbose: 'true', verifyReplicaCount: 'true', waitTime: ''
   }
}
