apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: tomcat-react
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    creationTimestamp: null
    labels:
      application: jws-app1
      template: jws30-tomcat7-basic-s2i
      xpaas: 1.2.0
    name: jws-app1
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: jws-app1:latest
        namespace: 48-thomas-test
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      contextDir: tomcat-websocket-chat
      git:
        ref: master
        uri: https://github.com/thgrueneED/openshift-quickstarts.git
      type: Git
    strategy:
      sourceStrategy:
        env:
        - name: BUILD_NUMBER
          value: "21"
        forcePull: true
        from:
          kind: ImageStreamTag
          name: jboss-webserver30-tomcat7-openshift:1.2
          namespace: openshift
      type: Source
    triggers:
    - github:
        secret: yLQLFIul
      type: GitHub
    - generic:
        secret: fLf7cuiL
      type: Generic
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
  status:
    lastVersion: 0
