apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: tomcat-react
objects:
- apiVersion: v1
  kind: Route
  metadata:
    annotations:
      description: Route for application's http service.
      openshift.io/host.generated: "true"
    creationTimestamp: null
    labels:
      application: jws-app1
      template: jws30-tomcat7-basic-s2i
      xpaas: 1.2.0
    name: jws-app1
  spec:
    host: jws-app1-48-thomas-test.cloud.itandtel.at
    port:
      targetPort: 8080-tcp
    tls:
      termination: edge
    to:
      kind: Service
      name: jws-app1
      weight: 100
  status:
    ingress:
    - conditions:
      - lastTransitionTime: 2016-10-08T05:42:11Z
        status: "True"
        type: Admitted
      host: jws-app1-48-thomas-test.cloud.itandtel.at
      routerName: prod-router
