apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: tomcat-react
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/deployment.cancelled: "23"
    creationTimestamp: null
    labels:
      application: jws-app1
      template: jws30-tomcat7-basic-s2i
      xpaas: 1.2.0
    name: jws-app1
  spec:
    replicas: 1
    selector:
      deploymentConfig: jws-app1
    strategy:
      recreateParams:
        timeoutSeconds: 600
      resources: {}
      type: Recreate
    template:
      metadata:
        creationTimestamp: null
        labels:
          application: jws-app1
          deploymentConfig: jws-app1
        name: jws-app1
      spec:
        containers:
        - env:
          - name: JWS_ADMIN_USERNAME
            value: admin
          - name: JWS_ADMIN_PASSWORD
            value: admin
          image: 172.30.194.147:5000/48-thomas-test/jws-app1@sha256:14f748963c25e4fee27136afe20875ea5784d630571331310912368ce5504f29
          imagePullPolicy: Always
          name: jws-app1
          ports:
          - containerPort: 8778
            name: jolokia
            protocol: TCP
          - containerPort: 8080
            name: http
            protocol: TCP
          readinessProbe:
            exec:
              command:
              - /bin/bash
              - -c
              - curl -s -u admin:admin 'http://localhost:8080/manager/jmxproxy/?get=Catalina%3Atype%3DServer&att=stateName'
                |grep -iq 'stateName *= *STARTED'
            failureThreshold: 3
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources: {}
          terminationMessagePath: /dev/termination-log
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 60
    test: false
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - jws-app1
        from:
          kind: ImageStreamTag
          name: jws-app1:latest
          namespace: 48-thomas-test
      type: ImageChange
    - type: ConfigChange
  status: {}
