apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: tomcat-react
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    creationTimestamp: null
    generation: 9
    labels:
      application: jws-app1
      template: jws30-tomcat7-basic-s2i
      xpaas: 1.2.0
    name: jws-app1
  spec:
    tags:
    - annotations: null
      from:
        kind: DockerImage
        name: 172.30.194.147:5000/48-thomas-test/jws-app1:17
      generation: 3
      importPolicy: {}
      name: "17"
    - annotations: null
      from:
        kind: DockerImage
        name: 172.30.194.147:5000/48-thomas-test/jws-app1:18
      generation: 4
      importPolicy: {}
      name: "18"
    - annotations: null
      from:
        kind: DockerImage
        name: 172.30.194.147:5000/48-thomas-test/jws-app1:19
      generation: 5
      importPolicy: {}
      name: "19"
    - annotations: null
      from:
        kind: DockerImage
        name: 172.30.194.147:5000/48-thomas-test/jws-app1:20
      generation: 6
      importPolicy: {}
      name: "20"
    - annotations: null
      from:
        kind: DockerImage
        name: 172.30.194.147:5000/48-thomas-test/jws-app1:21
      generation: 7
      importPolicy: {}
      name: "21"
    - annotations: null
      from:
        kind: DockerImage
        name: 172.30.194.147:5000/48-thomas-test/jws-app1:latest
      generation: null
      importPolicy: {}
      name: latest
    - annotations: null
      from:
        kind: DockerImage
        name: 172.30.194.147:5000/48-thomas-test/jws-app1:prod
      generation: 9
      importPolicy: {}
      name: prod
  status:
    dockerImageRepository: ""
